apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tic4303-mini-project-pvc
  namespace: tic4303-mini-project-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
