apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tic4303-mini-project-rolebinding
  namespace: tic4303-mini-project-namespace
subjects:
  - kind: ServiceAccount
    name: tic4303-mini-project-sa
    namespace: tic4303-mini-project-namespace
roleRef:
  kind: Role
  name: tic4303-mini-project-role
  apiGroup: rbac.authorization.k8s.io
   # Security: RoleBinding links the service account to the Role, ensuring that permissions apply only within this namespace and for this application.
