apiVersion: v1
kind: Service
metadata:
  name: tic4303-mini-project-service
  namespace: tic4303-mini-project-namespace
spec:
  selector:
    app: tic4303-mini-project
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
